import { createContext, useContext, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'language';

const translations = {
  ENG: {
    'language.switch': 'Switch language',
    'language.english': 'English',
    'language.vietnamese': 'Vietnamese',
    'header.categories': 'Categories',
    'header.signIn': 'Sign In',
    'header.signUp': 'Sign Up',
    'header.allCourses': 'All Courses',
    'header.myCart': 'My Cart',
    'header.myCourse': 'My Course',
    'header.loading': 'Loading...',
    'header.searchCourses': 'Search courses',
    'header.searchError': 'Could not search courses',
    'header.noCourseFound': 'No course found',
    'header.teachOnByway': 'Teach on Byway',
    'header.myAdmin': 'My Admin',
    'header.myProfile': 'My Profile',
    'header.myCourses': 'My Courses',
    'header.logOut': 'Log Out',
    'header.logIn': 'Log In',
    'header.openNotifications': 'Open notifications',
    'footer.tagline': 'Empowering learners through accessible and engaging online education.',
    'footer.description': 'Byway is a leading online learning platform dedicated to providing high-quality, flexible, and affordable educational experiences.',
    'footer.getHelp': 'Get Help',
    'footer.contactUs': 'Contact Us',
    'footer.latestArticles': 'Latest Articles',
    'footer.faq': 'FAQ',
    'footer.programs': 'Programs',
    'footer.address': 'Address',
    'footer.tel': 'Tel',
    'footer.mail': 'Mail',
    'home.loading': 'Loading...',
    'home.error': 'Could not load the homepage',
    'home.unlock': 'Unlock Your Potential with Byway',
    'home.welcome': "Welcome to Byway, where learning knows no bounds. We believe that education is the key to personal and professional growth, and we're here to guide you on your journey to success. Whether you're a student, professional, or lifelong learner, our cutting-edge Learning Management System is designed to elevate your learning experience.",
    'home.startInstructor': 'Start your instructor journey',
    'home.coursesByMentors': 'Courses by our best mentors',
    'home.topCategories': 'Top Categories',
    'home.courses': 'Courses',
    'home.topCourses': 'Top Courses',
    'home.topInstructors': 'Top Instructors',
    'home.customerReviews': 'What customers say about us',
    'home.becomeInstructor': 'Become an Instructor',
    'home.instructorDescription': 'Instructors from around the world teach millions of students on Byway. We provide the tools and skills to teach what you love.',
    'home.startInstructorJourney': 'Start Your Instructor Journey',
    'home.transformLife': 'Transform your life through education',
    'home.learnerDescription': 'Learners around the world are launching new careers, advancing in their fields, and enriching their lives.',
    'home.checkoutCourses': 'Checkout Courses',
    'home.completion': 'Completion rate of our courses',
    'course.filter': 'Filter',
    'course.courses': 'Courses',
    'course.sortBy': 'Sort By',
    'course.relevance': 'Relevance',
    'course.highestRated': 'Highest Rated',
    'course.priceLow': 'Price: Low to High',
    'course.priceHigh': 'Price: High to Low',
    'course.newest': 'Newest',
    'course.rating': 'Rating',
    'course.chapters': 'Number of Chapters',
    'course.price': 'Price',
    'course.category': 'Category',
    'course.seeMore': 'See More',
    'course.under50': 'Under $50',
    'course.noMatch': 'No courses match your filters.',
    'course.topInstructor': 'Top Instructor',
    'course.totalHours': 'Total Hours',
    'course.lectures': 'Lectures',
    'course.by': 'By',
    'cart.shoppingCart': 'Shopping Cart',
    'cart.details': 'Details',
    'cart.empty': 'Your cart is empty. Start shopping to add courses!',
    'cart.browse': 'Browse Courses',
    'cart.courseInCart': 'course in cart',
    'cart.coursesInCart': 'courses in cart',
    'cart.save': 'Save for later',
    'cart.savedForLater': 'Saved for later',
    'cart.moveToCart': 'Move to cart',
    'cart.remove': 'Remove',
    'cart.orderDetails': 'Order Details',
    'cart.discount': 'Discount',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'checkout.title': 'Checkout Page',
    'checkout.country': 'Country',
    'checkout.countryPlaceholder': 'Enter Country',
    'checkout.state': 'State / Union Territory',
    'checkout.statePlaceholder': 'Enter State',
    'checkout.locationRequired': 'Please enter both Country and State / Union Territory before proceeding to checkout.',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.momoWallet': 'MoMo wallet',
    'checkout.domesticAtm': 'Domestic ATM card',
    'checkout.internationalCard': 'International card (Visa/Mastercard)',
    'checkout.scanQr': 'Scan QR with MoMo wallet',
    'checkout.vnpay': 'VNPay',
    'checkout.applyCoupon': 'APPLY COUPON CODE',
    'checkout.apply': 'Apply',
    'checkout.applying': 'Applying...',
    'checkout.remove': 'Remove',
    'checkout.courseImageAlt': 'Course',
    'checkout.proceed': 'Proceed to Checkout',
    'checkout.processing': 'Processing...',
    'checkout.couponApplied': 'Coupon "{code}" applied',
    'wishlist.title': 'Your Wishlist',
    'wishlist.count.one': '{count} favorite course',
    'wishlist.count.many': '{count} favorite courses',
    'wishlist.empty': "You haven't saved any courses yet.",
    'wishlist.browse': 'Browse Courses',
    'wishlist.remove': 'Remove',
    'admin.management': 'Management',
    'admin.overview': 'Overview',
    'admin.courses': 'Courses',
    'admin.approvals': 'Course Approvals',
    'admin.events': 'Events',
    'admin.instructors': 'Instructors',
    'admin.accounts': 'Accounts',
    'admin.testimonials': 'Testimonials',
    'admin.featuredTeam': 'Featured instructor team',
    'admin.instructorCount': '{count} instructors',
    'admin.realTimeMetrics': 'Real-time platform metrics',
    'admin.manageCourses': 'Manage all courses on Byway',
    'admin.reviewSubmissions': 'Review and moderate pending course submissions',
    'admin.manageEvents': 'Create and manage events and minigames for students',
    'admin.registeredUsers': 'Registered users',
    'admin.featuredRatings': 'Featured ratings',
    'admin.totalCourses': 'Total courses',
    'admin.accountsLabel': 'Accounts',
    'admin.averageRating': 'Average rating',
    'admin.sortBy': 'Sort by',
    'admin.ratingHigh': 'Rating: 5 → 1 stars',
    'admin.ratingLow': 'Rating: 1 → 5 stars',
    'admin.studentsHigh': 'Students: high → low',
    'admin.studentsLow': 'Students: low → high',
    'admin.ratingLabel': 'rating',
    'admin.studentsLabel': 'students',
    'admin.courseOnByway': 'course on Byway',
    'admin.coursesOnByway': 'courses on Byway',
    'auth.signInTitle': 'Sign in to your account',
    'auth.usernameOrEmail': 'Username or Email',
    'auth.usernamePlaceholder': 'Username or Email ID',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter Password',
    'auth.signingIn': 'Signing in...',
    'auth.signIn': 'Sign In',
    'auth.signInWith': 'Sign in with',
    'auth.invalidCredentials': 'Wrong username/email or password',
    'auth.accountSuspended': 'This account is temporarily suspended.',
    'auth.oauthSessionExpired': 'The social sign-in session expired. Please try again.',
    'auth.oauthCancelled': 'Social sign-in was cancelled.',
    'auth.oauthUnavailable': 'This social sign-in provider is not configured.',
    'auth.oauthFailed': 'Could not complete social sign-in.',
    'auth.createAccount': 'Create Your Account',
    'auth.fullName': 'Full Name',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.username': 'Username',
    'auth.emailId': 'Email ID',
    'auth.confirmPassword': 'Confirm Password',
    'auth.continue': 'Continue',
    'auth.checking': 'Checking...',
    'auth.signUpWith': 'Sign up with',
    'auth.required': 'Please fill this field',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.usernameTaken': 'This username is already in use.',
    'auth.emailTaken': 'This email is already in use.',
    'auth.usernameEmailTaken': 'This username and email are already in use.',
    'auth.registrationFailed': 'Registration failed. Please check your information and try again.',
    'auth.registrationCheckFailed': 'Could not check registration information.',
    'auth.connectionFailed': 'Could not connect to the server.',
    'auth.interestRequired': 'Please choose at least one area of interest.',
    'auth.levelRequired': 'Please choose your current level.',
    'auth.expertiseRequired': 'Please enter your teaching expertise.',
    'auth.experienceRequired': 'Please enter your years of experience.',
    'auth.experienceInvalid': 'Years of experience must be 0 or greater.',
    'auth.bioRequired': 'Please provide a brief introduction.',
    'auth.fileLimit': 'You can choose up to 3 files.',
    'auth.fileTypes': 'Only PDF, JPG, or PNG files are accepted.',
    'auth.roleQuestion': 'You are a...',
    'auth.roleHint': 'You can change this later in settings',
    'auth.student': 'Student',
    'auth.studentDescription': 'Explore and learn courses from various fields',
    'auth.teacher': 'Teacher',
    'auth.teacherDescription': 'Create, manage, and sell your own courses',
    'profile.profile': 'Profile',
    'profile.myCourses': 'My Courses',
    'profile.teachers': 'Teachers',
    'profile.students': 'Students',
    'profile.message': 'Message',
    'profile.myReviews': 'My Reviews',
    'profile.share': 'Share Profile',
    'profile.shareText': 'View @{username} public profile on Byway',
    'profile.shareSuccess': 'Shared',
    'profile.shareError': 'Could not share',
    'profile.createCourse': 'Create Course',
    'publicProfile.loading': 'Loading public profile...',
    'publicProfile.notFound': 'This public profile is not available.',
    'publicProfile.backHome': 'Back to home',
    'publicProfile.publicBadge': 'Public profile',
    'publicProfile.teacher': 'Instructor',
    'publicProfile.learner': 'Learner',
    'publicProfile.rating': 'Rating',
    'publicProfile.students': 'Students',
    'publicProfile.courses': 'Courses',
    'publicProfile.privacyNote': 'Only public profile information is shown. Email and account codes are kept private.',
    'detail.home': 'Home',
    'detail.addToCart': 'Add To Cart',
    'detail.addedToCart': 'Added to Cart',
    'detail.alreadyInCart': 'Course already in cart!',
    'detail.buyNow': 'Buy Now',
    'detail.saved': 'Saved',
    'detail.addWishlist': 'Add to Wishlist',
    'detail.learnNow': 'Learn Now',
    'detail.createdBy': 'Created by',
    'detail.allLevels': 'All levels',
    'detail.description': 'Description',
    'detail.courseDescription': 'Course Description',
    'detail.certification': 'Certification',
    'detail.instructor': 'Instructor',
    'detail.syllabus': 'Syllabus',
    'detail.reviews': 'Reviews',
    'detail.learnerReviews': 'Learner Reviews',
    'detail.viewMoreReviews': 'View more Reviews',
    'detail.viewLessReviews': 'Show fewer Reviews',
    'detail.moreCourses': 'More Courses Like This',
    'detail.share': 'Share',
    'detail.sections': 'sections',
    'detail.lessons': 'lessons',
    'detail.hoursTotal': 'hours total',
    'detail.reviewCount': '{count} reviews',
    'detail.students': 'Students',
    'detail.courses': 'Courses',
    'learning.courseCompletion': 'Course Completion',
    'learning.details': 'Details',
    'learning.instructor': 'Instructor',
    'learning.courses': 'Courses',
    'learning.reviews': 'Reviews',
    'learning.courseDescription': 'Course Description',
    'learning.certification': 'Certification',
    'learning.moreCourses': 'More Courses Like This',
    'learning.quiz': 'Quiz',
    'learning.submitQuiz': 'Submit quiz',
    'learning.submitting': 'Submitting...',
    'learning.continueLearning': 'Continue learning',
    'learning.tryAgain': 'Try again',
    'learning.loading': 'Loading...',
    'learning.notFound': 'Course data not found.',
    'learning.reviews': 'Reviews',
    'learning.leaveReview': 'Leave your comments here',
    'learning.commentPlaceholder': 'Your comment here',
    'learning.sending': 'Sending...',
    'learning.sendRating': 'Send rating',
    'learning.reviewedOn': 'Reviewed on',
  },
  VIE: {
    'language.switch': 'Đổi ngôn ngữ',
    'language.english': 'Tiếng Anh',
    'language.vietnamese': 'Tiếng Việt',
    'header.categories': 'Danh mục',
    'header.signIn': 'Đăng nhập',
    'header.signUp': 'Đăng ký',
    'header.allCourses': 'Tất cả khóa học',
    'header.myCart': 'Giỏ hàng',
    'header.myCourse': 'Khóa học của tôi',
    'header.loading': 'Đang tải...',
    'header.searchCourses': 'Tìm kiếm khóa học',
    'header.searchError': 'Không thể tìm kiếm khóa học',
    'header.noCourseFound': 'Không tìm thấy khóa học',
    'header.teachOnByway': 'Dạy học trên Byway',
    'header.myAdmin': 'Trang quản trị',
    'header.myProfile': 'Hồ sơ của tôi',
    'header.myCourses': 'Khóa học của tôi',
    'header.logOut': 'Đăng xuất',
    'header.logIn': 'Đăng nhập',
    'header.openNotifications': 'Mở thông báo',
    'footer.tagline': 'Trao quyền học tập với nền giáo dục trực tuyến dễ tiếp cận và hấp dẫn.',
    'footer.description': 'Byway là nền tảng học trực tuyến cung cấp trải nghiệm giáo dục chất lượng cao, linh hoạt và hợp lý.',
    'footer.getHelp': 'Trợ giúp',
    'footer.contactUs': 'Liên hệ',
    'footer.latestArticles': 'Bài viết mới nhất',
    'footer.faq': 'Câu hỏi thường gặp',
    'footer.programs': 'Chương trình',
    'footer.address': 'Địa chỉ',
    'footer.tel': 'Điện thoại',
    'footer.mail': 'Email',
    'home.loading': 'Đang tải...',
    'home.error': 'Không thể tải trang chủ',
    'home.unlock': 'Khai phá tiềm năng cùng Byway',
    'home.welcome': 'Chào mừng đến với Byway, nơi việc học không có giới hạn. Chúng tôi tin rằng giáo dục là chìa khóa cho sự phát triển cá nhân và nghề nghiệp, đồng thời sẵn sàng đồng hành cùng bạn trên hành trình thành công.',
    'home.startInstructor': 'Bắt đầu hành trình giảng dạy',
    'home.coursesByMentors': 'Khóa học từ những cố vấn hàng đầu',
    'home.topCategories': 'Danh mục nổi bật',
    'home.courses': 'Khóa học',
    'home.topCourses': 'Khóa học nổi bật',
    'home.topInstructors': 'Giảng viên nổi bật',
    'home.customerReviews': 'Học viên nói gì về chúng tôi',
    'home.becomeInstructor': 'Trở thành giảng viên',
    'home.instructorDescription': 'Giảng viên trên toàn thế giới đang giảng dạy cho hàng triệu học viên trên Byway. Chúng tôi cung cấp công cụ và kỹ năng để bạn truyền đạt điều mình yêu thích.',
    'home.startInstructorJourney': 'Bắt đầu hành trình giảng dạy',
    'home.transformLife': 'Thay đổi cuộc sống qua giáo dục',
    'home.learnerDescription': 'Học viên trên toàn thế giới đang bắt đầu sự nghiệp mới, phát triển chuyên môn và làm phong phú cuộc sống.',
    'home.checkoutCourses': 'Xem khóa học',
    'home.completion': 'Tỷ lệ hoàn thành khóa học',
    'course.filter': 'Bộ lọc',
    'course.courses': 'Khóa học',
    'course.sortBy': 'Sắp xếp theo',
    'course.relevance': 'Liên quan',
    'course.highestRated': 'Đánh giá cao nhất',
    'course.priceLow': 'Giá: thấp đến cao',
    'course.priceHigh': 'Giá: cao đến thấp',
    'course.newest': 'Mới nhất',
    'course.rating': 'Đánh giá',
    'course.chapters': 'Số chương',
    'course.price': 'Giá',
    'course.category': 'Danh mục',
    'course.seeMore': 'Xem thêm',
    'course.under50': 'Dưới 50 USD',
    'course.noMatch': 'Không có khóa học phù hợp với bộ lọc.',
    'course.topInstructor': 'Giảng viên nổi bật',
    'course.totalHours': 'Tổng số giờ',
    'course.lectures': 'bài giảng',
    'course.by': 'Bởi',
    'cart.shoppingCart': 'Giỏ hàng',
    'cart.details': 'Chi tiết',
    'cart.empty': 'Giỏ hàng đang trống. Hãy mua sắm để thêm khóa học!',
    'cart.browse': 'Xem khóa học',
    'cart.courseInCart': 'khóa học trong giỏ',
    'cart.coursesInCart': 'khóa học trong giỏ',
    'cart.save': 'Lưu để xem sau',
    'cart.savedForLater': 'Đã lưu để xem sau',
    'cart.moveToCart': 'Chuyển vào giỏ',
    'cart.remove': 'Xóa',
    'cart.orderDetails': 'Chi tiết đơn hàng',
    'cart.discount': 'Giảm giá',
    'cart.tax': 'Thuế',
    'cart.total': 'Tổng cộng',
    'cart.checkout': 'Tiến hành thanh toán',
    'checkout.title': 'Trang thanh toán',
    'checkout.country': 'Quốc gia',
    'checkout.countryPlaceholder': 'Nhập quốc gia',
    'checkout.state': 'Tỉnh / Bang / Thành phố',
    'checkout.statePlaceholder': 'Nhập tỉnh / bang / thành phố',
    'checkout.locationRequired': 'Vui lòng nhập đầy đủ Quốc gia và Tỉnh / Bang / Thành phố trước khi thanh toán.',
    'checkout.paymentMethod': 'Phương thức thanh toán',
    'checkout.momoWallet': 'Ví MoMo',
    'checkout.domesticAtm': 'Thẻ ATM nội địa',
    'checkout.internationalCard': 'Thẻ quốc tế (Visa/Mastercard)',
    'checkout.scanQr': 'Quét mã QR bằng ví MoMo',
    'checkout.vnpay': 'VNPay',
    'checkout.applyCoupon': 'NHẬP MÃ GIẢM GIÁ',
    'checkout.apply': 'Áp dụng',
    'checkout.applying': 'Đang áp dụng...',
    'checkout.remove': 'Xóa',
    'checkout.courseImageAlt': 'Khóa học',
    'checkout.proceed': 'Tiến hành thanh toán',
    'checkout.processing': 'Đang xử lý...',
    'checkout.couponApplied': 'Đã áp dụng mã "{code}"',
    'wishlist.title': 'Danh sách yêu thích',
    'wishlist.count.one': '{count} khóa học yêu thích',
    'wishlist.count.many': '{count} khóa học yêu thích',
    'wishlist.empty': 'Bạn chưa lưu khóa học nào.',
    'wishlist.browse': 'Xem khóa học',
    'wishlist.remove': 'Xóa',
    'admin.management': 'QUẢN LÝ',
    'admin.overview': 'Tổng quan',
    'admin.courses': 'Khóa học',
    'admin.approvals': 'Duyệt khóa học',
    'admin.events': 'Sự kiện',
    'admin.instructors': 'Giảng viên',
    'admin.accounts': 'Tài khoản',
    'admin.testimonials': 'Đánh giá',
    'admin.featuredTeam': 'Đội ngũ giảng viên nổi bật',
    'admin.instructorCount': '{count} giảng viên',
    'admin.realTimeMetrics': 'Số liệu nền tảng theo thời gian thực',
    'admin.manageCourses': 'Quản lý toàn bộ khóa học trên Byway',
    'admin.reviewSubmissions': 'Xem xét và kiểm duyệt khóa học đang chờ',
    'admin.manageEvents': 'Tạo và quản lý sự kiện, minigame cho học viên',
    'admin.registeredUsers': 'Người dùng đã đăng ký',
    'admin.featuredRatings': 'Đánh giá nổi bật',
    'admin.totalCourses': 'Tổng số khóa học',
    'admin.accountsLabel': 'Tài khoản',
    'admin.averageRating': 'Đánh giá trung bình',
    'admin.sortBy': 'Sắp xếp theo',
    'admin.ratingHigh': 'Đánh giá: 5 → 1 sao',
    'admin.ratingLow': 'Đánh giá: 1 → 5 sao',
    'admin.studentsHigh': 'Học viên: nhiều → ít',
    'admin.studentsLow': 'Học viên: ít → nhiều',
    'admin.ratingLabel': 'đánh giá',
    'admin.studentsLabel': 'học viên',
    'admin.courseOnByway': 'khóa học trên Byway',
    'admin.coursesOnByway': 'khóa học trên Byway',
    'auth.signInTitle': 'Đăng nhập vào tài khoản',
    'auth.usernameOrEmail': 'Tên người dùng hoặc Email',
    'auth.usernamePlaceholder': 'Nhập tên người dùng hoặc Email',
    'auth.password': 'Mật khẩu',
    'auth.passwordPlaceholder': 'Nhập mật khẩu',
    'auth.signingIn': 'Đang đăng nhập...',
    'auth.signIn': 'Đăng nhập',
    'auth.signInWith': 'Đăng nhập bằng',
    'auth.invalidCredentials': 'Sai tên người dùng/email hoặc mật khẩu',
    'auth.accountSuspended': 'Tài khoản này đang bị tạm khóa.',
    'auth.oauthSessionExpired': 'Phiên đăng nhập mạng xã hội đã hết hạn. Vui lòng thử lại.',
    'auth.oauthCancelled': 'Bạn đã hủy đăng nhập mạng xã hội.',
    'auth.oauthUnavailable': 'Nhà cung cấp đăng nhập mạng xã hội này chưa được cấu hình.',
    'auth.oauthFailed': 'Không thể hoàn tất đăng nhập mạng xã hội.',
    'auth.createAccount': 'Tạo tài khoản',
    'auth.fullName': 'Họ và tên',
    'auth.firstName': 'Tên',
    'auth.lastName': 'Họ',
    'auth.username': 'Tên người dùng',
    'auth.emailId': 'Địa chỉ Email',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.continue': 'Tiếp tục',
    'auth.checking': 'Đang kiểm tra...',
    'auth.signUpWith': 'Đăng ký bằng',
    'auth.required': 'Vui lòng điền trường này',
    'auth.passwordMismatch': 'Mật khẩu không khớp',
    'auth.usernameTaken': 'Tên người dùng này đã được sử dụng.',
    'auth.emailTaken': 'Email này đã được sử dụng.',
    'auth.usernameEmailTaken': 'Tên người dùng và email này đã được sử dụng.',
    'auth.registrationFailed': 'Đăng ký thất bại. Vui lòng kiểm tra thông tin và thử lại.',
    'auth.registrationCheckFailed': 'Không thể kiểm tra thông tin đăng ký.',
    'auth.connectionFailed': 'Không thể kết nối đến máy chủ.',
    'auth.interestRequired': 'Vui lòng chọn ít nhất một lĩnh vực bạn quan tâm.',
    'auth.levelRequired': 'Vui lòng chọn trình độ hiện tại của bạn.',
    'auth.expertiseRequired': 'Vui lòng nhập chuyên môn giảng dạy.',
    'auth.experienceRequired': 'Vui lòng nhập số năm kinh nghiệm.',
    'auth.experienceInvalid': 'Số năm kinh nghiệm phải từ 0 trở lên.',
    'auth.bioRequired': 'Vui lòng giới thiệu ngắn gọn về bạn.',
    'auth.fileLimit': 'Bạn chỉ có thể chọn tối đa 3 tệp.',
    'auth.fileTypes': 'Chỉ chấp nhận tệp PDF, JPG hoặc PNG.',
    'auth.roleQuestion': 'Bạn là...',
    'auth.roleHint': 'Bạn có thể thay đổi lựa chọn này trong phần cài đặt',
    'auth.student': 'Học viên',
    'auth.studentDescription': 'Khám phá và học các khóa học từ nhiều lĩnh vực',
    'auth.teacher': 'Giảng viên',
    'auth.teacherDescription': 'Tạo, quản lý và bán khóa học của riêng bạn',
    'profile.profile': 'Hồ sơ',
    'profile.myCourses': 'Khóa học của tôi',
    'profile.teachers': 'Giảng viên',
    'profile.students': 'Học viên',
    'profile.message': 'Tin nhắn',
    'profile.myReviews': 'Đánh giá của tôi',
    'profile.share': 'Chia sẻ hồ sơ',
    'profile.shareText': 'Xem hồ sơ công khai @{username} trên Byway',
    'profile.shareSuccess': 'Đã chia sẻ',
    'profile.shareError': 'Không thể chia sẻ',
    'profile.createCourse': 'Tạo khóa học',
    'publicProfile.loading': 'Đang tải hồ sơ công khai...',
    'publicProfile.notFound': 'Hồ sơ công khai này không tồn tại.',
    'publicProfile.backHome': 'Về trang chủ',
    'publicProfile.publicBadge': 'Hồ sơ công khai',
    'publicProfile.teacher': 'Giảng viên',
    'publicProfile.learner': 'Học viên',
    'publicProfile.rating': 'Đánh giá',
    'publicProfile.students': 'Học viên',
    'publicProfile.courses': 'Khóa học',
    'publicProfile.privacyNote': 'Chỉ hiển thị thông tin công khai. Email và mã tài khoản được giữ riêng tư.',
    'detail.home': 'Trang chủ',
    'detail.addToCart': 'Thêm vào giỏ hàng',
    'detail.addedToCart': 'Đã thêm vào giỏ hàng',
    'detail.alreadyInCart': 'Khóa học đã có trong giỏ hàng!',
    'detail.buyNow': 'Mua ngay',
    'detail.saved': 'Đã lưu',
    'detail.addWishlist': 'Thêm vào yêu thích',
    'detail.learnNow': 'Học ngay',
    'detail.createdBy': 'Tạo bởi',
    'detail.allLevels': 'Mọi cấp độ',
    'detail.description': 'Mô tả',
    'detail.courseDescription': 'Mô tả khóa học',
    'detail.certification': 'Chứng chỉ',
    'detail.instructor': 'Giảng viên',
    'detail.syllabus': 'Giáo trình',
    'detail.reviews': 'Đánh giá',
    'detail.learnerReviews': 'Đánh giá của học viên',
    'detail.viewMoreReviews': 'Xem thêm đánh giá',
    'detail.viewLessReviews': 'Thu gọn đánh giá',
    'detail.moreCourses': 'Khóa học tương tự',
    'detail.share': 'Chia sẻ',
    'detail.sections': 'phần',
    'detail.lessons': 'bài học',
    'detail.hoursTotal': 'tổng số giờ',
    'detail.reviewCount': '{count} đánh giá',
    'detail.students': 'Học viên',
    'detail.courses': 'Khóa học',
    'learning.courseCompletion': 'Tiến độ khóa học',
    'learning.details': 'Chi tiết',
    'learning.instructor': 'Giảng viên',
    'learning.courses': 'Giáo trình',
    'learning.reviews': 'Đánh giá',
    'learning.courseDescription': 'Mô tả khóa học',
    'learning.certification': 'Chứng chỉ',
    'learning.moreCourses': 'Khóa học tương tự',
    'learning.quiz': 'Bài kiểm tra',
    'learning.submitQuiz': 'Nộp bài kiểm tra',
    'learning.submitting': 'Đang nộp...',
    'learning.continueLearning': 'Tiếp tục học',
    'learning.tryAgain': 'Thử lại',
    'learning.loading': 'Đang tải...',
    'learning.notFound': 'Không tìm thấy dữ liệu khóa học.',
    'learning.leaveReview': 'Hãy để lại nhận xét của bạn',
    'learning.commentPlaceholder': 'Nhập nhận xét của bạn',
    'learning.sending': 'Đang gửi...',
    'learning.sendRating': 'Gửi đánh giá',
    'learning.reviewedOn': 'Đánh giá vào ngày',
  },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  if (typeof window === 'undefined') return 'ENG';
  const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return saved === 'VIE' || saved === 'ENG' ? saved : 'ENG';
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  const value = useMemo(() => {
    const dictionary = translations[language] || translations.ENG;
    const t = (key, variables = {}) => {
      const template = dictionary[key] || translations.ENG[key] || key;
      return Object.entries(variables).reduce(
        (result, [name, replacement]) => result.replace(`{${name}}`, String(replacement)),
        template,
      );
    };

    const changeLanguage = (nextLanguage) => {
      const next = nextLanguage === 'VIE' ? 'VIE' : 'ENG';
      setLanguage(next);
      localStorage.setItem(LANGUAGE_STORAGE_KEY, next);
    };

    return {
      language,
      setLanguage: changeLanguage,
      toggleLanguage: () => changeLanguage(language === 'ENG' ? 'VIE' : 'ENG'),
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
